# Generated by Django 4.1.4 on 2022-12-26 15:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default/avatar.svg",
                upload_to=users.models.CustomUser.image_upload_to,
            ),
        ),
    ]
