# Generated by Django 4.1.4 on 2022-12-26 16:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default/dennis.jpg",
                upload_to=users.models.CustomUser.image_upload_to,
            ),
        ),
    ]
