# Generated by Django 4.1.4 on 2023-01-01 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                ("slug", models.SlugField(unique=True, verbose_name="Series-slug")),
                (
                    "published",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date-published"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/dennis.jpg",
                        max_length=255,
                        upload_to=main_app.models.ArticleSeries.image_upload_to,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Series",
                "ordering": ["-published"],
            },
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                (
                    "article_slug",
                    models.SlugField(unique=True, verbose_name="Article-slug"),
                ),
                ("content", tinymce.models.HTMLField(blank=True, default="")),
                ("notes", tinymce.models.HTMLField(blank=True, default="")),
                (
                    "published",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date-published"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date-modified"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/dennis.jpg",
                        max_length=255,
                        upload_to=main_app.models.Articles.image_upload_to,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main_app.articleseries",
                        verbose_name="Series",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Articles",
                "ordering": ["-published"],
            },
        ),
    ]
