# Generated by Django 4.1.4 on 2022-12-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="content",
            field=models.TextField(
                blank=True, default="", max_length=600, verbose_name="content"
            ),
        ),
    ]
