# Generated by Django 4.1.4 on 2022-12-25 19:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_articles_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="notes",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="articles",
            name="content",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
