# Generated by Django 4.1.4 on 2022-12-26 15:36

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_articles_author_articleseries_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleseries",
            name="image",
            field=models.ImageField(
                default="default/avatar.svg",
                max_length=255,
                upload_to=main_app.models.ArticleSeries.image_upload_to,
            ),
        ),
    ]
