# Generated by Django 4.1.4 on 2022-12-26 16:43

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_alter_articleseries_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="image",
            field=models.ImageField(
                default="default/no_image.jpg",
                max_length=255,
                upload_to=main_app.models.Articles.image_upload_to,
            ),
        ),
    ]
