# Generated by Django 4.1.4 on 2022-12-27 09:04

from django.db import migrations, models
import django.utils.timezone
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_articles_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="articles",
            name="image",
            field=models.ImageField(
                default="default/dennis.jpg",
                max_length=255,
                upload_to=main_app.models.Articles.image_upload_to,
            ),
        ),
    ]
